spring:
  profiles:
    active: local

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: ${ADMIN_MAIL}
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 3_600_000
  refresh-token-expiration-minutes: 604_800_000